const fs = require('fs');
console.log('=== app.js ===');
fs.readFileSync('js/app.js','utf8').split('\n').forEach((l,i)=>{ if (/GamMonetag|adMonetagDirectHTML/.test(l)) console.log((i+1)+': '+JSON.stringify(l)); });
console.log('=== gam.js ===');
fs.readFileSync('js/gam.js','utf8').split('\n').forEach((l,i)=>{ if (/GamMonetag/.test(l)) console.log((i+1)+': '+JSON.stringify(l)); });
console.log('=== index.html aclib ===');
const c = fs.readFileSync('index.html','utf8');
const k = c.indexOf('aclib');
console.log('firstAclibIdx='+k);
console.log(k>=0 ? JSON.stringify(c.slice(Math.max(0,k-40), k+400)) : '');
